# Generated by Django 4.2.15 on 2024-08-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_src',
            field=models.CharField(default='https://www.google.com/search?sca_esv=32e484f6156eb8e3&rlz=1C5GCEM_enBG1122BG1122&q=apple+image&tbm=isch&source=lnms&fbs=AEQNm0Aa4sjWe7Rqy32pFwRj0UkWERaHdBms7t-tHL1116ec0FnDIxrxgGhNFSZEtYqV91TSiNw_7vO1mgUQ5ZBeky6VGxnZQ_IiLYK56P0Zpj03KysDZT5PGg9mBQAs3JsQeehb-6g_re6JgQFRoQ7-5PdNxcruZPRKrJ6AVfeSwlM4eq84-pw8jcnU__gidphJF81we6BV&sa=X&ved=2ahUKEwiGv4SqweWHAxX8SPEDHQLzEyAQ0pQJegQIFBAB&biw=1440&bih=703&dpr=2#imgrc=ktcxvF5LaXyVXM', max_length=1000),
        ),
    ]
